### ISSUE TITLE
protocols.io Coronavirus Method Dev Community

### ISSUE THREAD

**Issue by kapsakcj** [dmaccannell/SARS-CoV-2seq#2]
Just got an email regarding a group within protocols.io for methods development for SARS-CoV2

Might be useful to add a link in here?

https://www.protocols.io/groups/coronavirus-method-development-community

body of email:

"The science community is working hard to address the potential health crisis brought about by the outbreak of a novel coronavirus (COVID-19). Sharing research methods is a critical part of accelerating COVID-19 research. To support these efforts, protocols.io has set up a method development community and our editorial team is ready to help import protocols into the COVID-19 group

Email your protocol PDF/document to “info@protocols.io”. An editor will enter it, another will check it, and we'll privately reassign it to you for review/publishing.
  
Or join the Coronavirus Method Development Community group to receive updates, add resources or start discussions."

**Comment by dmaccannell** [comment]
Will add. I've directly linked to a number of the protocols.io submissions, but should probably put something on there about the group, and how to submit. Protocols.io is a fantastic platform.  Thanks, CK
